### ISSUE TITLE
When referring the controller file absolute path getting the follow error

### ISSUE THREAD

**Issue by riginoommen** [sap9433/yoSapy#1]
? Absolute path of the File to be tested /home/roommen/training/myController.js

events.js:160
      throw er; // Unhandled 'error' event
      ^
AssertionError: Trying to copy from a source that does not exist: /usr/lib/node_modules/generator-yosapy/app/templates/undefined.js
    at EditionInterface.exports._copySingle (/usr/lib/node_modules/generator-yosapy/node_modules/mem-fs-editor/actions/copy.js:44:3)
    at EditionInterface.exports.copy (/usr/lib/node_modules/generator-yosapy/node_modules/mem-fs-editor/actions/copy.js:22:17)
    at EditionInterface.module.exports [as copyTpl] (/usr/lib/node_modules/generator-yosapy/node_modules/mem-fs-editor/actions/copy-tpl.js:9:8)
    at child.writing (/usr/lib/node_modules/generator-yosapy/app/index.js:45:17)
    at /usr/lib/node_modules/generator-yosapy/node_modules/yeoman-generator/lib/base.js:409:16
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by riginoommen** [comment]
@sap9433 , @vaeroon , @crashuniverse can some one help me

**Comment by karendolan** [comment]
The code expects "/controllers/" or "/directives/" to be part of the Absolute path of the File to be tested.  https://github.com/sap9433/yoSapy/blob/master/app/index.js#L25
(IMHO, an improvement would be to pass a param arg "controller" or "directive" when launching.)
